/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.MyCombobox;
import static GUI.pnldonbanhang.cbbSize1;
import static GUI.pnldonbanhang.pop3;

/**
 *
 * @author KMB1604
 */
public class pnlShowSanPham extends javax.swing.JPanel {

    /**
     * Creates new form jdlShowItem
     */
    public pnlShowSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        jScrollPane5.setBorder(null);

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tìm kiếm 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItem.setRowHeight(25);
        tblItem.setShowHorizontalLines(false);
        tblItem.setShowVerticalLines(false);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
           if (evt.getClickCount() == 1) {
              int dongduocchon = tblItem.getSelectedRow();
            if (dongduocchon >= 0) {
            pnldonbanhang.cbbSize1.setEnabled(true);
            pnldonbanhang.cbbMau1.setEnabled(true);   
            }
            }
        
        try {

            int column = 0;
            int row = tblItem.getSelectedRow();
            String value = tblItem.getModel().getValueAt(row, column).toString();

            BLL.BLLSanPham.SizeSanPhamTheoTen( pnldonbanhang.cbbSize1, value);
            MyCombobox mbs = (MyCombobox)  pnldonbanhang.cbbSize1.getSelectedItem();
            int MaSize = Integer.parseInt(mbs.Value.toString());
            System.out.println(MaSize);
            BLL.BLLSanPham.MauSanPhamTheoTen(pnldonbanhang.cbbMau1, value, MaSize);
            pnldonbanhang.txtTextValue.setText(value);
           pop3.setVisible(false);
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
